name: Our Add
description: add two numbers
inputs:
  num-a:
    default: 3
  num-b:
    default: 7
outputs:
  result:
    value: ${{ steps.sum.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.num-a }} ${{ inputs.num-b }}"
      shell: bash
    - run: echo "result=$((${{ inputs.num-a }} + ${{ inputs.num-b }}))">> "$GITHUB_OUTPUT"
      id: sum
      shell: bash
