name: Our Calc
description: calculate two numbers
inputs:
  x:
    default: 3
  y:
    default: 7
outputs:
  plus:
    value: ${{ steps.plus.outputs.result }}
  minus:
    value: ${{ steps.minus.outputs.result }}
  multiply:
    value: ${{ steps.multiply.outputs.result }}
  divide:
    value: ${{ steps.divide.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: echo "x=${{ inputs.x }} y=${{ inputs.y }}"
      shell: bash
    - id: plus
      run: echo "result=$((${{ inputs.x }} + ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: minus
      run: echo "result=$((${{ inputs.x }} - ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: multiply
      run: echo "result=$((${{ inputs.x }} * ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: divide
      run: echo "result=$((${{ inputs.x }} / ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      shell: bash
