name: Our Add
description: add two numbers
inputs:
  x:
    default: 3
  y:
    default: 7
outputs:
  plus:
    value: ${{ steps.plus.outputs.result }}
  minus:
    value: ${{ steps.minus.outputs.result }}
  multiply:
    value: ${{ steps.multiply.outputs.result }}
  divide:
    value: ${{ steps.divide.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: echo "x=${{ inputs.x }} y=${{ inputs.y }}))"
      shell: bash
    - run: echo "result=$((${{ inputs.x }} + ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      id: plus
      shell: bash
    - run: echo "result=$((${{ inputs.x }} - ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      id: minus
      shell: bash
    - run: echo "result=$((${{ inputs.x }} * ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      id: multiply
      shell: bash
    - run: echo "result=$((${{ inputs.x }} / ${{ inputs.y }}))" >> "$GITHUB_OUTPUT"
      id: divide
      shell: bash
