name: Our Workflow
on: push
jobs:
  caculate:
    runs-on: ubuntu-latest
    steps:
      - id: calc
        uses: DaleSchool/calc-action@main
        with:
          x: 12
          y: 3
      - run: echo "x + y = ${{ steps.calc.outputs.plus }}"
      - run: echo "x - y = ${{ steps.calc.outputs.minus }}"

#     steps:
#       - uses: actions/checkout@v3
#       - uses: ./.github/actions/calc
#         id: calc
#         with:
#           x: 16
#           y: 5
#       - run: echo "plus=${{ steps.calc.outputs.plus }}"
#       - run: echo "minus=${{ steps.calc.outputs.minus }}"
#       - run: echo "multiply=${{ steps.calc.outputs.plus }}"
#       - run: echo "divide=${{ steps.calc.outputs.divide }}"
